sparkVersion=4.0.2
minSupportedJavaVersion=17
supportedEmrVersion=emr-7.0.0
unsupportedMinorSparkVersions=
scalaVersion=2.13.16
databricksVersion=16.0.x-cpu-ml-scala2.13
fabricK8sClientVersion=6.4.1
executorOverheadMemoryOption=spark.executor.memoryOverhead
driverOverheadMemoryOption=spark.driver.memoryOverhead
supportedPythonVersions=3.9 3.10 3.11
