sparkVersion=4.2.0
minSupportedJavaVersion=17
supportedEmrVersion=emr-7.0.0
unsupportedMinorSparkVersions=
scalaVersion=2.13.17
databricksVersion=16.0.x-cpu-ml-scala2.13
fabricK8sClientVersion=7.5.2
executorOverheadMemoryOption=spark.executor.memoryOverhead
driverOverheadMemoryOption=spark.driver.memoryOverhead
supportedPythonVersions=3.9 3.10 3.11
